let Settings = document.getElementById("Settings");
let Dashboard = document.getElementById("Dashboard");
let Profile = document.getElementById("Profile");
let Projects = document.getElementById("Projects");
let Courses = document.getElementById("Courses");
let Friends = document.getElementById("Friends");
let Files = document.getElementById("Files");
let Plans = document.getElementById("Plans");

let Dashboard_click = document.getElementById("Dashboard_click");
let Settings_click = document.getElementById("Settings_click");
let Profile_click = document.getElementById("Profile_click");
let Projects_click = document.getElementById("Projects_click");
let Courses_click = document.getElementById("Courses_click");
let friends_click = document.getElementById("friends_click");
let Files_click = document.getElementById("Files_click");
let Plans_click = document.getElementById("Plans_click");

let Dashboard_i = document.getElementById("Dashboard_i");
let Dashboard_a = document.getElementById("Dashboard_a");
let Settings_i = document.getElementById("Settings_i");
let Settings_a = document.getElementById("Settings_a");
let Profile_i = document.getElementById("Profile_i");
let Profile_a = document.getElementById("Profile_a");
let Projects_i = document.getElementById("Projects_i");
let Projects_a = document.getElementById("Projects_a");
let Courses_i = document.getElementById("Courses_i");
let Courses_a = document.getElementById("Courses_a");
let Friends_i = document.getElementById("friends_i");
let Friends_a = document.getElementById("friends_a");
let Files_i = document.getElementById("Files_i");
let Files_a = document.getElementById("Files_a");
let Plans_i = document.getElementById("Plans_i");
let Plans_a = document.getElementById("Plans_a");


Dashboard_click.onclick = function () {
    Dashboard.setAttribute('style', 'display:block !important');
    Settings.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Plans.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Dashboard_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
} 
Settings_click.onclick = function () {
    Settings.setAttribute('style', 'display:block !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Plans.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Settings_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
Profile_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:block !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Plans.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Profile_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
Projects_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:block !important');
    Plans.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Projects_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
Courses_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:block !important');
    Plans.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Courses_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
friends_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:block !important');
    Plans.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Friends_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
Files_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:block !important');
    Plans.setAttribute('style', 'display:none !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Files_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Plans_i.setAttribute('style', 'color:wight !important');
    Plans_a.setAttribute('style', 'color:wight !important');
}
Plans_click.onclick = function () {
    Settings.setAttribute('style', 'display:none !important');
    Dashboard.setAttribute('style', 'display:none !important');
    Profile.setAttribute('style', 'display:none !important');
    Projects.setAttribute('style', 'display:none !important');
    Courses.setAttribute('style', 'display:none !important');
    Friends.setAttribute('style', 'display:none !important');
    Files.setAttribute('style', 'display:none !important');
    Plans.setAttribute('style', 'display:block !important');
    Dashboard_i.setAttribute('style', 'color:wight !important');
    Dashboard_a.setAttribute('style', 'color:wight !important');
    Settings_i.setAttribute('style', 'color:wight !important');
    Settings_a.setAttribute('style', 'color:wight !important');
    Profile_i.setAttribute('style', 'color:wight !important');
    Profile_a.setAttribute('style', 'color:wight !important');
    Projects_i.setAttribute('style', 'color:wight !important');
    Projects_a.setAttribute('style', 'color:wight !important');
    Courses_i.setAttribute('style', 'color:wight !important');
    Courses_a.setAttribute('style', 'color:wight !important');
    Friends_i.setAttribute('style', 'color:wight !important');
    Friends_a.setAttribute('style', 'color:wight !important');
    Files_i.setAttribute('style', 'color:wight !important');
    Files_a.setAttribute('style', 'color:wight !important');
    Plans_i.setAttribute('style', 'color:rgb(15, 149, 238) !important');
    Plans_a.setAttribute('style', 'color:rgb(15, 149, 238) !important');
}



